export const input = {
  layouts: [
    {
      borderXPadding: 28,
      elementXPadding: 32,
      id: 'originalLayout',
      borderYPadding: 32,
      isOptimised: false,
      isEdited: false,
      canvasWidth: 1080,
      userRating: 0,
      canvasHeight: 1920,
      elementYPadding: 32,
      score: 0,
      elements: [
        {
          id: '<HeadingImageElement: 0x600003b616c0>',
          horizontalPreference: 'None',
          verticalPreference: 'Top',
          x: -1,
          fillColorGreenValue: 255,
          y: -1,
          isDrawingFill: 1,
          width: 1015,
          type: 'HeadingImageElement',
          fillColorBlueValue: 103,
          fillColorRedValue: 34,
          isLocked: 'false',
          height: 140,
        },
        {
          id: '<ImageElement: 0x600003b5c540>',
          horizontalPreference: 'None',
          verticalPreference: 'None',
          x: -1,
          fillColorGreenValue: 255,
          y: -1,
          isDrawingFill: 1,
          width: 1016,
          type: 'ImageElement',
          fillColorBlueValue: 255,
          fillColorRedValue: 255,
          isLocked: 'false',
          height: 549,
        },
        {
          id: '<FormFieldImageElement: 0x600003bb00e0>',
          horizontalPreference: 'None',
          verticalPreference: 'None',
          x: -1,
          fillColorGreenValue: 255,
          y: -1,
          isDrawingFill: 1,
          width: 481,
          type: 'FormFieldImageElement',
          fillColorBlueValue: 255,
          fillColorRedValue: 255,
          isLocked: 'false',
          height: 128,
        },
        {
          id: '<ParagraphImageElement: 0x600003b61a40>',
          horizontalPreference: 'None',
          verticalPreference: 'None',
          x: -1,
          fillColorGreenValue: 255,
          y: -1,
          isDrawingFill: 1,
          width: 904,
          type: 'ParagraphImageElement',
          fillColorBlueValue: 255,
          fillColorRedValue: 255,
          isLocked: 'false',
          height: 623,
        },
        {
          id: '<HeadingImageElement: 0x600003b55960>',
          horizontalPreference: 'None',
          verticalPreference: 'Bottom',
          x: -1,
          fillColorGreenValue: 66,
          y: -1,
          isDrawingFill: 1,
          width: 1022,
          type: 'HeadingImageElement',
          fillColorBlueValue: 72,
          fillColorRedValue: 68,
          isLocked: 'false',
          height: 198,
        },
        {
          id: '<FormFieldImageElement: 0x600003bb0000>',
          horizontalPreference: 'None',
          verticalPreference: 'None',
          x: -1,
          fillColorGreenValue: 255,
          y: -1,
          isDrawingFill: 1,
          width: 447,
          type: 'FormFieldImageElement',
          fillColorBlueValue: 255,
          fillColorRedValue: 255,
          isLocked: 'false',
          height: 128,
        },
      ],
      isSaved: false,
    },
  ],
};

export const output1 = {
  layouts: [
    {
      objectiveValue: 40.038,
      canvasWidth: 1080,
      canvasHeight: 1920,
      id: 'a1',
      elements: [
        {
          x: 35.0,
          y: 32.0,
          width: 1015.0,
          height: 140.0,
          id: '<HeadingImageElement: 0x600003b616c0>',
          type: 'HeadingImageElement',
          verticalPreference: 'Top',
          horizontalPreference: 'None',
          fillColorRedValue: 34,
          fillColorGreenValue: 255,
          fillColorBlueValue: 103,
          isLocked: 'false',
        },
        {
          x: 34.0,
          y: 204.0,
          width: 1016.0,
          height: 549.0,
          id: '<ImageElement: 0x600003b5c540>',
          type: 'ImageElement',
          verticalPreference: 'None',
          horizontalPreference: 'None',
          fillColorRedValue: 255,
          fillColorGreenValue: 255,
          fillColorBlueValue: 255,
          isLocked: 'false',
        },
        {
          x: 507.0,
          y: 785.0,
          width: 481.0,
          height: 128.0,
          id: '<FormFieldImageElement: 0x600003bb00e0>',
          type: 'FormFieldImageElement',
          verticalPreference: 'None',
          horizontalPreference: 'None',
          fillColorRedValue: 255,
          fillColorGreenValue: 255,
          fillColorBlueValue: 255,
          isLocked: 'false',
        },
        {
          x: 146.0,
          y: 945.0,
          width: 904.0,
          height: 623.0,
          id: '<ParagraphImageElement: 0x600003b61a40>',
          type: 'ParagraphImageElement',
          verticalPreference: 'None',
          horizontalPreference: 'None',
          fillColorRedValue: 255,
          fillColorGreenValue: 255,
          fillColorBlueValue: 255,
          isLocked: 'false',
        },
        {
          x: 28.0,
          y: 1600.0,
          width: 1022.0,
          height: 198.0,
          id: '<HeadingImageElement: 0x600003b55960>',
          type: 'HeadingImageElement',
          verticalPreference: 'Bottom',
          horizontalPreference: 'None',
          fillColorRedValue: 68,
          fillColorGreenValue: 66,
          fillColorBlueValue: 72,
          isLocked: 'false',
        },
        {
          x: 28.0,
          y: 785.0,
          width: 447.0,
          height: 128.0,
          id: '<FormFieldImageElement: 0x600003bb0000>',
          type: 'FormFieldImageElement',
          verticalPreference: 'None',
          horizontalPreference: 'None',
          fillColorRedValue: 255,
          fillColorGreenValue: 255,
          fillColorBlueValue: 255,
          isLocked: 'false',
        },
      ],
    },
  ],
};

export const output2 = {
  layouts: [
    {
      objectiveValue: 37.068,
      canvasWidth: 1080,
      canvasHeight: 1920,
      id: 'a2',
      elements: [
        {
          x: 36.0,
          y: 32.0,
          width: 1015.0,
          height: 140.0,
          id: '<HeadingImageElement: 0x600003b616c0>',
          type: 'HeadingImageElement',
          verticalPreference: 'Top',
          horizontalPreference: 'None',
          fillColorRedValue: 34,
          fillColorGreenValue: 255,
          fillColorBlueValue: 103,
          isLocked: 'false',
        },
        {
          x: 35.0,
          y: 364.0,
          width: 1016.0,
          height: 549.0,
          id: '<ImageElement: 0x600003b5c540>',
          type: 'ImageElement',
          verticalPreference: 'None',
          horizontalPreference: 'None',
          fillColorRedValue: 255,
          fillColorGreenValue: 255,
          fillColorBlueValue: 255,
          isLocked: 'false',
        },
        {
          x: 514.0,
          y: 204.0,
          width: 481.0,
          height: 128.0,
          id: '<FormFieldImageElement: 0x600003bb00e0>',
          type: 'FormFieldImageElement',
          verticalPreference: 'None',
          horizontalPreference: 'None',
          fillColorRedValue: 255,
          fillColorGreenValue: 255,
          fillColorBlueValue: 255,
          isLocked: 'false',
        },
        {
          x: 147.0,
          y: 945.0,
          width: 904.0,
          height: 623.0,
          id: '<ParagraphImageElement: 0x600003b61a40>',
          type: 'ParagraphImageElement',
          verticalPreference: 'None',
          horizontalPreference: 'None',
          fillColorRedValue: 255,
          fillColorGreenValue: 255,
          fillColorBlueValue: 255,
          isLocked: 'false',
        },
        {
          x: 29.0,
          y: 1600.0,
          width: 1022.0,
          height: 198.0,
          id: '<HeadingImageElement: 0x600003b55960>',
          type: 'HeadingImageElement',
          verticalPreference: 'Bottom',
          horizontalPreference: 'None',
          fillColorRedValue: 68,
          fillColorGreenValue: 66,
          fillColorBlueValue: 72,
          isLocked: 'false',
        },
        {
          x: 29.0,
          y: 204.0,
          width: 447.0,
          height: 128.0,
          id: '<FormFieldImageElement: 0x600003bb0000>',
          type: 'FormFieldImageElement',
          verticalPreference: 'None',
          horizontalPreference: 'None',
          fillColorRedValue: 255,
          fillColorGreenValue: 255,
          fillColorBlueValue: 255,
          isLocked: 'false',
        },
      ],
    },
  ],
};

export const output3 = {
  layouts: [
    {
      objectiveValue: 37.065,
      canvasWidth: 1080,
      canvasHeight: 1920,
      id: 'a3',
      elements: [
        {
          x: 36.0,
          y: 32.0,
          width: 1015.0,
          height: 140.0,
          id: '<HeadingImageElement: 0x600003b616c0>',
          type: 'HeadingImageElement',
          verticalPreference: 'Top',
          horizontalPreference: 'None',
          fillColorRedValue: 34,
          fillColorGreenValue: 255,
          fillColorBlueValue: 103,
          isLocked: 'false',
        },
        {
          x: 35.0,
          y: 364.0,
          width: 1016.0,
          height: 549.0,
          id: '<ImageElement: 0x600003b5c540>',
          type: 'ImageElement',
          verticalPreference: 'None',
          horizontalPreference: 'None',
          fillColorRedValue: 255,
          fillColorGreenValue: 255,
          fillColorBlueValue: 255,
          isLocked: 'false',
        },
        {
          x: 513.0,
          y: 204.0,
          width: 481.0,
          height: 128.0,
          id: '<FormFieldImageElement: 0x600003bb00e0>',
          type: 'FormFieldImageElement',
          verticalPreference: 'None',
          horizontalPreference: 'None',
          fillColorRedValue: 255,
          fillColorGreenValue: 255,
          fillColorBlueValue: 255,
          isLocked: 'false',
        },
        {
          x: 147.0,
          y: 945.0,
          width: 904.0,
          height: 623.0,
          id: '<ParagraphImageElement: 0x600003b61a40>',
          type: 'ParagraphImageElement',
          verticalPreference: 'None',
          horizontalPreference: 'None',
          fillColorRedValue: 255,
          fillColorGreenValue: 255,
          fillColorBlueValue: 255,
          isLocked: 'false',
        },
        {
          x: 29.0,
          y: 1600.0,
          width: 1022.0,
          height: 198.0,
          id: '<HeadingImageElement: 0x600003b55960>',
          type: 'HeadingImageElement',
          verticalPreference: 'Bottom',
          horizontalPreference: 'None',
          fillColorRedValue: 68,
          fillColorGreenValue: 66,
          fillColorBlueValue: 72,
          isLocked: 'false',
        },
        {
          x: 29.0,
          y: 204.0,
          width: 447.0,
          height: 128.0,
          id: '<FormFieldImageElement: 0x600003bb0000>',
          type: 'FormFieldImageElement',
          verticalPreference: 'None',
          horizontalPreference: 'None',
          fillColorRedValue: 255,
          fillColorGreenValue: 255,
          fillColorBlueValue: 255,
          isLocked: 'false',
        },
      ],
    },
  ],
};
