export const example = [
  {
    _class: 'rectangle',
    do_objectID: '66821A79-F728-491C-B87A-1714C88E0E5D',
    booleanOperation: -1,
    isFixedToViewport: false,
    isFlippedHorizontal: false,
    isFlippedVertical: false,
    isLocked: false,
    isVisible: true,
    layerListExpandedType: 0,
    name: '矩形',
    nameIsFixed: false,
    resizingConstraint: 63,
    resizingType: 0,
    rotation: 0,
    shouldBreakMaskChain: false,
    exportOptions: {
      _class: 'exportOptions',
      includedLayerIds: [],
      layerOptions: 0,
      shouldTrim: false,
      exportFormats: [],
    },
    frame: {
      _class: 'rect',
      constrainProportions: false,
      height: 50,
      width: 100,
      x: 187,
      y: 286,
    },
    clippingMaskMode: 0,
    hasClippingMask: false,
    style: {
      _class: 'style',
      do_objectID: '65FC9A82-6FFC-4C03-9842-05CEC348416A',
      endMarkerType: 0,
      miterLimit: 10,
      startMarkerType: 0,
      windingRule: 1,
      blur: {
        _class: 'blur',
        isEnabled: false,
        center: '{0.5, 0.5}',
        motionAngle: 0,
        radius: 10,
        saturation: 1,
        type: 0,
      },
      borderOptions: {
        _class: 'borderOptions',
        isEnabled: true,
        dashPattern: [],
        lineCapStyle: 0,
        lineJoinStyle: 0,
      },
      borders: [
        {
          _class: 'border',
          isEnabled: false,
          fillType: 0,
          color: {
            _class: 'color',
            alpha: 1,
            blue: 0.592,
            green: 0.592,
            red: 0.592,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 0,
            opacity: 1,
          },
          gradient: {
            _class: 'gradient',
            elipseLength: 0,
            from: '{0.5, 0}',
            gradientType: 0,
            to: '{0.5, 1}',
            stops: [
              {
                _class: 'gradientStop',
                position: 0,
                color: {
                  _class: 'color',
                  alpha: 1,
                  blue: 1,
                  green: 1,
                  red: 1,
                },
              },
              {
                _class: 'gradientStop',
                position: 1,
                color: {
                  _class: 'color',
                  alpha: 1,
                  blue: 0,
                  green: 0,
                  red: 0,
                },
              },
            ],
          },
          position: 1,
          thickness: 1,
        },
      ],
      colorControls: {
        _class: 'colorControls',
        isEnabled: false,
        brightness: 0,
        contrast: 1,
        hue: 0,
        saturation: 1,
      },
      contextSettings: {
        _class: 'graphicsContextSettings',
        blendMode: 0,
        opacity: 1,
      },
      fills: [
        {
          _class: 'fill',
          isEnabled: true,
          fillType: 0,
          color: {
            _class: 'color',
            alpha: 1,
            blue: 0.6528221187004988,
            green: 0.6528221187004988,
            red: 0.7786741394927537,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 0,
            opacity: 1,
          },
          gradient: {
            _class: 'gradient',
            elipseLength: 0,
            from: '{0.5, 0}',
            gradientType: 0,
            to: '{0.5, 1}',
            stops: [
              {
                _class: 'gradientStop',
                position: 0,
                color: {
                  _class: 'color',
                  alpha: 1,
                  blue: 1,
                  green: 1,
                  red: 1,
                },
              },
              {
                _class: 'gradientStop',
                position: 1,
                color: {
                  _class: 'color',
                  alpha: 1,
                  blue: 0,
                  green: 0,
                  red: 0,
                },
              },
            ],
          },
          noiseIndex: 0,
          noiseIntensity: 0,
          patternFillType: 1,
          patternTileScale: 1,
        },
      ],
      innerShadows: [
        {
          _class: 'innerShadow',
          isEnabled: true,
          blurRadius: 8,
          offsetX: 0,
          offsetY: 5,
          spread: 12,
          color: {
            _class: 'color',
            alpha: 0.5,
            blue: 0.6706012228260869,
            green: 0.1650946608024589,
            red: 0.3087320968320091,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 0,
            opacity: 1,
          },
        },
      ],
      shadows: [
        {
          _class: 'shadow',
          isEnabled: true,
          blurRadius: 4,
          offsetX: 0,
          offsetY: 2,
          spread: 0,
          color: {
            _class: 'color',
            alpha: 0.5,
            blue: 0,
            green: 0,
            red: 0,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 9,
            opacity: 1,
          },
        },
        {
          _class: 'shadow',
          isEnabled: true,
          blurRadius: 4,
          offsetX: 0,
          offsetY: 2,
          spread: 8,
          color: {
            _class: 'color',
            alpha: 0.5,
            blue: 0,
            green: 0,
            red: 1,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 0,
            opacity: 1,
          },
        },
      ],
    },
    edited: false,
    isClosed: true,
    pointRadiusBehaviour: 1,
    points: [
      {
        _class: 'curvePoint',
        cornerRadius: 0,
        curveFrom: '{0, 0}',
        curveMode: 1,
        curveTo: '{0, 0}',
        hasCurveFrom: false,
        hasCurveTo: false,
        point: '{0, 0}',
      },
      {
        _class: 'curvePoint',
        cornerRadius: 0,
        curveFrom: '{1, 0}',
        curveMode: 1,
        curveTo: '{1, 0}',
        hasCurveFrom: false,
        hasCurveTo: false,
        point: '{1, 0}',
      },
      {
        _class: 'curvePoint',
        cornerRadius: 0,
        curveFrom: '{1, 1}',
        curveMode: 1,
        curveTo: '{1, 1}',
        hasCurveFrom: false,
        hasCurveTo: false,
        point: '{1, 1}',
      },
      {
        _class: 'curvePoint',
        cornerRadius: 0,
        curveFrom: '{0, 1}',
        curveMode: 1,
        curveTo: '{0, 1}',
        hasCurveFrom: false,
        hasCurveTo: false,
        point: '{0, 1}',
      },
    ],
    fixedRadius: 0,
    needsConvertionToNewRoundCorners: false,
    hasConvertedToNewRoundCorners: true,
  },
  {
    _class: 'rectangle',
    do_objectID: '52471B8A-7B25-4F39-A0E4-E3E5F4EEF650',
    booleanOperation: -1,
    isFixedToViewport: false,
    isFlippedHorizontal: false,
    isFlippedVertical: false,
    isLocked: false,
    isVisible: true,
    layerListExpandedType: 0,
    name: '矩形备份',
    nameIsFixed: false,
    resizingConstraint: 63,
    resizingType: 0,
    rotation: 0,
    shouldBreakMaskChain: false,
    exportOptions: {
      _class: 'exportOptions',
      includedLayerIds: [],
      layerOptions: 0,
      shouldTrim: false,
      exportFormats: [],
    },
    frame: {
      _class: 'rect',
      constrainProportions: false,
      height: 50,
      width: 100,
      x: 381,
      y: 286,
    },
    clippingMaskMode: 0,
    hasClippingMask: false,
    style: {
      _class: 'style',
      do_objectID: 'DA7C59AA-8BBC-4916-9439-900C1F75B805',
      endMarkerType: 0,
      miterLimit: 10,
      startMarkerType: 0,
      windingRule: 1,
      blur: {
        _class: 'blur',
        isEnabled: false,
        center: '{0.5, 0.5}',
        motionAngle: 0,
        radius: 10,
        saturation: 1,
        type: 0,
      },
      borderOptions: {
        _class: 'borderOptions',
        isEnabled: true,
        dashPattern: [],
        lineCapStyle: 0,
        lineJoinStyle: 0,
      },
      borders: [
        {
          _class: 'border',
          isEnabled: false,
          fillType: 0,
          color: {
            _class: 'color',
            alpha: 1,
            blue: 0.592,
            green: 0.592,
            red: 0.592,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 0,
            opacity: 1,
          },
          gradient: {
            _class: 'gradient',
            elipseLength: 0,
            from: '{0.5, 0}',
            gradientType: 0,
            to: '{0.5, 1}',
            stops: [
              {
                _class: 'gradientStop',
                position: 0,
                color: {
                  _class: 'color',
                  alpha: 1,
                  blue: 1,
                  green: 1,
                  red: 1,
                },
              },
              {
                _class: 'gradientStop',
                position: 1,
                color: {
                  _class: 'color',
                  alpha: 1,
                  blue: 0,
                  green: 0,
                  red: 0,
                },
              },
            ],
          },
          position: 1,
          thickness: 1,
        },
      ],
      colorControls: {
        _class: 'colorControls',
        isEnabled: false,
        brightness: 0,
        contrast: 1,
        hue: 0,
        saturation: 1,
      },
      contextSettings: {
        _class: 'graphicsContextSettings',
        blendMode: 0,
        opacity: 1,
      },
      fills: [
        {
          _class: 'fill',
          isEnabled: true,
          fillType: 0,
          color: {
            _class: 'color',
            alpha: 1,
            blue: 0.6528221187004988,
            green: 0.6528221187004988,
            red: 0.7786741394927537,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 0,
            opacity: 1,
          },
          gradient: {
            _class: 'gradient',
            elipseLength: 0,
            from: '{0.5, 0}',
            gradientType: 0,
            to: '{0.5, 1}',
            stops: [
              {
                _class: 'gradientStop',
                position: 0,
                color: {
                  _class: 'color',
                  alpha: 1,
                  blue: 1,
                  green: 1,
                  red: 1,
                },
              },
              {
                _class: 'gradientStop',
                position: 1,
                color: {
                  _class: 'color',
                  alpha: 1,
                  blue: 0,
                  green: 0,
                  red: 0,
                },
              },
            ],
          },
          noiseIndex: 0,
          noiseIntensity: 0,
          patternFillType: 1,
          patternTileScale: 1,
        },
      ],
      innerShadows: [
        {
          _class: 'innerShadow',
          isEnabled: true,
          blurRadius: 8,
          offsetX: 0,
          offsetY: 5,
          spread: 12,
          color: {
            _class: 'color',
            alpha: 0.5,
            blue: 0.6706012228260869,
            green: 0.1650946608024589,
            red: 0.3087320968320091,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 0,
            opacity: 1,
          },
        },
      ],
      shadows: [
        {
          _class: 'shadow',
          isEnabled: true,
          blurRadius: 4,
          offsetX: 0,
          offsetY: 2,
          spread: 0,
          color: {
            _class: 'color',
            alpha: 0.5,
            blue: 0,
            green: 0,
            red: 0,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 9,
            opacity: 1,
          },
        },
        {
          _class: 'shadow',
          isEnabled: true,
          blurRadius: 4,
          offsetX: 0,
          offsetY: 2,
          spread: 8,
          color: {
            _class: 'color',
            alpha: 0.5,
            blue: 0,
            green: 0,
            red: 1,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 0,
            opacity: 1,
          },
        },
      ],
    },
    edited: false,
    isClosed: true,
    pointRadiusBehaviour: 1,
    points: [
      {
        _class: 'curvePoint',
        cornerRadius: 0,
        curveFrom: '{0, 0}',
        curveMode: 1,
        curveTo: '{0, 0}',
        hasCurveFrom: false,
        hasCurveTo: false,
        point: '{0, 0}',
      },
      {
        _class: 'curvePoint',
        cornerRadius: 0,
        curveFrom: '{1, 0}',
        curveMode: 1,
        curveTo: '{1, 0}',
        hasCurveFrom: false,
        hasCurveTo: false,
        point: '{1, 0}',
      },
      {
        _class: 'curvePoint',
        cornerRadius: 0,
        curveFrom: '{1, 1}',
        curveMode: 1,
        curveTo: '{1, 1}',
        hasCurveFrom: false,
        hasCurveTo: false,
        point: '{1, 1}',
      },
      {
        _class: 'curvePoint',
        cornerRadius: 0,
        curveFrom: '{0, 1}',
        curveMode: 1,
        curveTo: '{0, 1}',
        hasCurveFrom: false,
        hasCurveTo: false,
        point: '{0, 1}',
      },
    ],
    fixedRadius: 0,
    needsConvertionToNewRoundCorners: false,
    hasConvertedToNewRoundCorners: true,
  },
  {
    _class: 'rectangle',
    do_objectID: '28BA8390-02A6-48EB-83C8-E3C5DD734013',
    booleanOperation: -1,
    isFixedToViewport: false,
    isFlippedHorizontal: false,
    isFlippedVertical: false,
    isLocked: false,
    isVisible: true,
    layerListExpandedType: 0,
    name: '矩形备份 2',
    nameIsFixed: false,
    resizingConstraint: 63,
    resizingType: 0,
    rotation: 0,
    shouldBreakMaskChain: false,
    exportOptions: {
      _class: 'exportOptions',
      includedLayerIds: [],
      layerOptions: 0,
      shouldTrim: false,
      exportFormats: [],
    },
    frame: {
      _class: 'rect',
      constrainProportions: false,
      height: 50,
      width: 100,
      x: 187,
      y: 387,
    },
    clippingMaskMode: 0,
    hasClippingMask: false,
    style: {
      _class: 'style',
      do_objectID: 'EC94B76A-631F-4521-B703-5E84DA587C6F',
      endMarkerType: 0,
      miterLimit: 10,
      startMarkerType: 0,
      windingRule: 1,
      blur: {
        _class: 'blur',
        isEnabled: false,
        center: '{0.5, 0.5}',
        motionAngle: 0,
        radius: 10,
        saturation: 1,
        type: 0,
      },
      borderOptions: {
        _class: 'borderOptions',
        isEnabled: true,
        dashPattern: [],
        lineCapStyle: 0,
        lineJoinStyle: 0,
      },
      borders: [
        {
          _class: 'border',
          isEnabled: false,
          fillType: 0,
          color: {
            _class: 'color',
            alpha: 1,
            blue: 0.592,
            green: 0.592,
            red: 0.592,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 0,
            opacity: 1,
          },
          gradient: {
            _class: 'gradient',
            elipseLength: 0,
            from: '{0.5, 0}',
            gradientType: 0,
            to: '{0.5, 1}',
            stops: [
              {
                _class: 'gradientStop',
                position: 0,
                color: {
                  _class: 'color',
                  alpha: 1,
                  blue: 1,
                  green: 1,
                  red: 1,
                },
              },
              {
                _class: 'gradientStop',
                position: 1,
                color: {
                  _class: 'color',
                  alpha: 1,
                  blue: 0,
                  green: 0,
                  red: 0,
                },
              },
            ],
          },
          position: 1,
          thickness: 1,
        },
      ],
      colorControls: {
        _class: 'colorControls',
        isEnabled: false,
        brightness: 0,
        contrast: 1,
        hue: 0,
        saturation: 1,
      },
      contextSettings: {
        _class: 'graphicsContextSettings',
        blendMode: 0,
        opacity: 1,
      },
      fills: [
        {
          _class: 'fill',
          isEnabled: true,
          fillType: 0,
          color: {
            _class: 'color',
            alpha: 1,
            blue: 0.6528221187004988,
            green: 0.6528221187004988,
            red: 0.7786741394927537,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 0,
            opacity: 1,
          },
          gradient: {
            _class: 'gradient',
            elipseLength: 0,
            from: '{0.5, 0}',
            gradientType: 0,
            to: '{0.5, 1}',
            stops: [
              {
                _class: 'gradientStop',
                position: 0,
                color: {
                  _class: 'color',
                  alpha: 1,
                  blue: 1,
                  green: 1,
                  red: 1,
                },
              },
              {
                _class: 'gradientStop',
                position: 1,
                color: {
                  _class: 'color',
                  alpha: 1,
                  blue: 0,
                  green: 0,
                  red: 0,
                },
              },
            ],
          },
          noiseIndex: 0,
          noiseIntensity: 0,
          patternFillType: 1,
          patternTileScale: 1,
        },
      ],
      innerShadows: [
        {
          _class: 'innerShadow',
          isEnabled: true,
          blurRadius: 8,
          offsetX: 0,
          offsetY: 5,
          spread: 12,
          color: {
            _class: 'color',
            alpha: 0.5,
            blue: 0.6706012228260869,
            green: 0.1650946608024589,
            red: 0.3087320968320091,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 0,
            opacity: 1,
          },
        },
      ],
      shadows: [
        {
          _class: 'shadow',
          isEnabled: true,
          blurRadius: 4,
          offsetX: 0,
          offsetY: 2,
          spread: 0,
          color: {
            _class: 'color',
            alpha: 0.5,
            blue: 0,
            green: 0,
            red: 0,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 9,
            opacity: 1,
          },
        },
        {
          _class: 'shadow',
          isEnabled: true,
          blurRadius: 4,
          offsetX: 0,
          offsetY: 2,
          spread: 8,
          color: {
            _class: 'color',
            alpha: 0.5,
            blue: 0,
            green: 0,
            red: 1,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 0,
            opacity: 1,
          },
        },
      ],
    },
    edited: false,
    isClosed: true,
    pointRadiusBehaviour: 1,
    points: [
      {
        _class: 'curvePoint',
        cornerRadius: 0,
        curveFrom: '{0, 0}',
        curveMode: 1,
        curveTo: '{0, 0}',
        hasCurveFrom: false,
        hasCurveTo: false,
        point: '{0, 0}',
      },
      {
        _class: 'curvePoint',
        cornerRadius: 0,
        curveFrom: '{1, 0}',
        curveMode: 1,
        curveTo: '{1, 0}',
        hasCurveFrom: false,
        hasCurveTo: false,
        point: '{1, 0}',
      },
      {
        _class: 'curvePoint',
        cornerRadius: 0,
        curveFrom: '{1, 1}',
        curveMode: 1,
        curveTo: '{1, 1}',
        hasCurveFrom: false,
        hasCurveTo: false,
        point: '{1, 1}',
      },
      {
        _class: 'curvePoint',
        cornerRadius: 0,
        curveFrom: '{0, 1}',
        curveMode: 1,
        curveTo: '{0, 1}',
        hasCurveFrom: false,
        hasCurveTo: false,
        point: '{0, 1}',
      },
    ],
    fixedRadius: 0,
    needsConvertionToNewRoundCorners: false,
    hasConvertedToNewRoundCorners: true,
  },
  {
    _class: 'rectangle',
    do_objectID: '44332491-792B-417F-96BD-C7926F6F97F1',
    booleanOperation: -1,
    isFixedToViewport: false,
    isFlippedHorizontal: false,
    isFlippedVertical: false,
    isLocked: false,
    isVisible: true,
    layerListExpandedType: 0,
    name: '矩形备份 3',
    nameIsFixed: false,
    resizingConstraint: 63,
    resizingType: 0,
    rotation: 0,
    shouldBreakMaskChain: false,
    exportOptions: {
      _class: 'exportOptions',
      includedLayerIds: [],
      layerOptions: 0,
      shouldTrim: false,
      exportFormats: [],
    },
    frame: {
      _class: 'rect',
      constrainProportions: false,
      height: 50,
      width: 100,
      x: 381,
      y: 387,
    },
    clippingMaskMode: 0,
    hasClippingMask: false,
    style: {
      _class: 'style',
      do_objectID: '6E7A57F5-3CF8-4D76-A2D7-2F0594550629',
      endMarkerType: 0,
      miterLimit: 10,
      startMarkerType: 0,
      windingRule: 1,
      blur: {
        _class: 'blur',
        isEnabled: false,
        center: '{0.5, 0.5}',
        motionAngle: 0,
        radius: 10,
        saturation: 1,
        type: 0,
      },
      borderOptions: {
        _class: 'borderOptions',
        isEnabled: true,
        dashPattern: [],
        lineCapStyle: 0,
        lineJoinStyle: 0,
      },
      borders: [
        {
          _class: 'border',
          isEnabled: false,
          fillType: 0,
          color: {
            _class: 'color',
            alpha: 1,
            blue: 0.592,
            green: 0.592,
            red: 0.592,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 0,
            opacity: 1,
          },
          gradient: {
            _class: 'gradient',
            elipseLength: 0,
            from: '{0.5, 0}',
            gradientType: 0,
            to: '{0.5, 1}',
            stops: [
              {
                _class: 'gradientStop',
                position: 0,
                color: {
                  _class: 'color',
                  alpha: 1,
                  blue: 1,
                  green: 1,
                  red: 1,
                },
              },
              {
                _class: 'gradientStop',
                position: 1,
                color: {
                  _class: 'color',
                  alpha: 1,
                  blue: 0,
                  green: 0,
                  red: 0,
                },
              },
            ],
          },
          position: 1,
          thickness: 1,
        },
      ],
      colorControls: {
        _class: 'colorControls',
        isEnabled: false,
        brightness: 0,
        contrast: 1,
        hue: 0,
        saturation: 1,
      },
      contextSettings: {
        _class: 'graphicsContextSettings',
        blendMode: 0,
        opacity: 1,
      },
      fills: [
        {
          _class: 'fill',
          isEnabled: true,
          fillType: 0,
          color: {
            _class: 'color',
            alpha: 1,
            blue: 0.6528221187004988,
            green: 0.6528221187004988,
            red: 0.7786741394927537,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 0,
            opacity: 1,
          },
          gradient: {
            _class: 'gradient',
            elipseLength: 0,
            from: '{0.5, 0}',
            gradientType: 0,
            to: '{0.5, 1}',
            stops: [
              {
                _class: 'gradientStop',
                position: 0,
                color: {
                  _class: 'color',
                  alpha: 1,
                  blue: 1,
                  green: 1,
                  red: 1,
                },
              },
              {
                _class: 'gradientStop',
                position: 1,
                color: {
                  _class: 'color',
                  alpha: 1,
                  blue: 0,
                  green: 0,
                  red: 0,
                },
              },
            ],
          },
          noiseIndex: 0,
          noiseIntensity: 0,
          patternFillType: 1,
          patternTileScale: 1,
        },
      ],
      innerShadows: [
        {
          _class: 'innerShadow',
          isEnabled: true,
          blurRadius: 8,
          offsetX: 0,
          offsetY: 5,
          spread: 12,
          color: {
            _class: 'color',
            alpha: 0.5,
            blue: 0.6706012228260869,
            green: 0.1650946608024589,
            red: 0.3087320968320091,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 0,
            opacity: 1,
          },
        },
      ],
      shadows: [
        {
          _class: 'shadow',
          isEnabled: true,
          blurRadius: 4,
          offsetX: 0,
          offsetY: 2,
          spread: 0,
          color: {
            _class: 'color',
            alpha: 0.5,
            blue: 0,
            green: 0,
            red: 0,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 9,
            opacity: 1,
          },
        },
        {
          _class: 'shadow',
          isEnabled: true,
          blurRadius: 4,
          offsetX: 0,
          offsetY: 2,
          spread: 8,
          color: {
            _class: 'color',
            alpha: 0.5,
            blue: 0,
            green: 0,
            red: 1,
          },
          contextSettings: {
            _class: 'graphicsContextSettings',
            blendMode: 0,
            opacity: 1,
          },
        },
      ],
    },
    edited: false,
    isClosed: true,
    pointRadiusBehaviour: 1,
    points: [
      {
        _class: 'curvePoint',
        cornerRadius: 0,
        curveFrom: '{0, 0}',
        curveMode: 1,
        curveTo: '{0, 0}',
        hasCurveFrom: false,
        hasCurveTo: false,
        point: '{0, 0}',
      },
      {
        _class: 'curvePoint',
        cornerRadius: 0,
        curveFrom: '{1, 0}',
        curveMode: 1,
        curveTo: '{1, 0}',
        hasCurveFrom: false,
        hasCurveTo: false,
        point: '{1, 0}',
      },
      {
        _class: 'curvePoint',
        cornerRadius: 0,
        curveFrom: '{1, 1}',
        curveMode: 1,
        curveTo: '{1, 1}',
        hasCurveFrom: false,
        hasCurveTo: false,
        point: '{1, 1}',
      },
      {
        _class: 'curvePoint',
        cornerRadius: 0,
        curveFrom: '{0, 1}',
        curveMode: 1,
        curveTo: '{0, 1}',
        hasCurveFrom: false,
        hasCurveTo: false,
        point: '{0, 1}',
      },
    ],
    fixedRadius: 0,
    needsConvertionToNewRoundCorners: false,
    hasConvertedToNewRoundCorners: true,
  },
];
